### ISSUE TITLE
Scan text to clipboard

### ISSUE THREAD

**Issue by XaeonBE** [joecks/clipboard-actions-community#21]
Is there a way to ad a feature that lets me press a button in the persistant notification to open my camera and take a picture of text and add that text to my clipboard. So basicly a image to clipboard action?

**Comment by joecks** [comment]
Thanks for the request. OCR is a pretty complex task, do you know any app which is doing that right and good? Then I would love to integrate the other app with Clipboard Actions, otherwise I am not sure if I ever manage to build text detection.
