### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by joecks** [joecks/clipboard-actions-community#4]
Requests: 1

**Comment by joecks** [comment]
+1

**Comment by Rafa-and** [comment]
I can help you with Spanish.
I recommend using
https://www.oneskyapp.com/

**Comment by joecks** [comment]
Thanks for your help.
I have set up a collaborative system to translate the App. Since I am not
earning anything with the Clipboard Actions App I can not offer you any
anything in return, but to keep the App for free and mention your name :)

Here is the link to the translation tool:
https://poeditor.com/join/project/QJknOiXAF2



Also I would kindly ask you to accept to provide any translations under
CC Open Domain or CC By licence, so if you want I would mention your name
in the translators list
https://creativecommons.org/licenses/by/4.0/
https://creativecommons.org/publicdomain/zero/1.0/


Thanks
Simon

Rafa-and <notifications@github.com> schrieb am Di., 12. Jan. 2016 um
00:25 Uhr:

**Comment by Rafa-and** [comment]
Hi,

Yes, I accept it.  No problem at all.
Translation completed!

You can mention me as 'Rafael Corredor' (my real name).
Thank you

**Comment by Maikuolan** [comment]
> Here is the link to the translation tool:
> https://poeditor.com/join/project/QJknOiXAF2

Hi,

I found your repository by using the GitHub search functionality, and I'm replying in response to the above quoted text.

This possibly may be a terrible idea, I'm not sure, but, I've created a repository for a list just now for the purposes of listing GitHub repositories that are also registered with POEditor, that are looking for and/or willing to accept translators, available here -> https://github.com/Maikuolan/GitHub-OS-POEditor-Projects-List

Would you be interested in having your repository listed on this list, and would I have your permission to list it there? Cheers. :-)

PS, if this is a terrible idea, feel free to let me know or to just ignore my reply to this issue.

**Comment by joecks** [comment]
Yes thanks. It makes sense! Love it.

**Comment by Maikuolan** [comment]
Excellent! Glad to hear it, and added. :-)

**Comment by satchdaddy22** [comment]
![![](url)](

1. url

)
