### ISSUE TITLE
Android 6 - Accessibility for Clipboard Actions is randomly set to OFF

### ISSUE THREAD

**Issue by mirekgoldberg** [joecks/clipboard-actions-community#78]
Android 6.0.1 - Accessibility for Clipboard Actions is randomly set to OFF and I have to reset it manually to ON very often. I can't understand and pinpoint what mechanism does the switching OFF. Could it be other app(s) that also have their Accessibility enabled that in stealth disable Clipboard Actions because it competes with their purpose? Anyway, this behavior is quite annoying as I want Clipboard Actions Accessibility to be enabled at all times.

**Comment by Poppyfox** [comment]
I have this issue on my Z50310 running Android 8.1.0
It makes the app completely manual

**Comment by joecks** [comment]
Duplicated with #88 
Can anybody research that and suggest a solution?
