### ISSUE TITLE
[Feature] Import Export functionality

### ISSUE THREAD

**Issue by regschan** [joecks/clipboard-actions-community#79]
Can we have the option for Import and export. It'll be very beneficial while reinstalling the app or while switching to new device.

**Comment by bisht-sanjeet** [comment]
+9999

**Comment by Ilithy** [comment]
Hello,

This would be an extremely practical function, the possibility of exporting the entire clipboard in TXT or RTF format.
Convenient for saving, and importing...

Thank you very much.

**Comment by joecks** [comment]
Done from version 46
