### ISSUE TITLE
Constant attacks from the north so all my att goes to playing games with a miserable pissed off bunch of hackers that just act like juvenile punk. 

### ISSUE THREAD

**Issue by Dominoaffect68** [joecks/clipboard-actions-community#83]
Im silent and humble, and don't engage the circus act. The facts are the individual put city water account in my name, and had cloned my device, so i got the call about a water leak in north v., I told her i had a well and said its not my account ,she said for me to give her my account # and, no such thing, i dont have a account. So she gave me the letters and numbers on the curb in front of every house, they tell the guys who read the meeter and idetifies the property to match the serial # on the meeter, she gave it to me and i googled it it came back to a house that the lettuce farmer was living at, and his device is black listed on 15 diferent ips. And i made it a mission to hunt this rodent that hides in the house, and thinks im so dumb and could never find out, hahaha! 😁😈

**Comment by joecks** [comment]
Spam
