### ISSUE TITLE
Clipboard feature request

### ISSUE THREAD

**Issue by BJAdams** [joecks/clipboard-actions-community#85]
Dear Dev. Community,
Please ADD the SHARE feature (which launches all on device and other common sharing apps) allowing sharing directly from the app.
THANK YOU ONE AND ALL!

**Comment by Sarun515s** [comment]
#78 README.md

**Comment by joecks** [comment]
This is part of the app core functionality. Please specify.

**Comment by BJAdams** [comment]
Hi, Till H. I have a problem arising from my insistence of getting my OLD CD to display on my current laptop (Dell 13-9310)  running Microsoft 11 Pro. The CD app is 16-bit and the developer indicated I must buy a new CD in order to use the information on the CD. The information is entirely digital, I seem to recall; that is, there are no images (.jpeg, .mp4, .avi, etc.). Besides my parsimonious resistance to purchasing a new CD (licences) I have downloaded DOSBox and attempted to install the lates Android SDK v20.5 but the latter will not install on Windows (dumb me!) and the link to the DOSBox "mount" does not find the appropriate file (my bad!). Please provide guidance or precise code to enable "playing" the CD contents. THANK YOU in advance for whatever you can provide. Bill
