### ISSUE TITLE
Using adb permission to read logs on Android 10

### ISSUE THREAD

**Issue by xnegra80** [joecks/clipboard-actions-community#92]
I have seen another app which uses the adb READ_LOGS permission to read the clipboard globally. This might be a better way to work around instead of using a quick settings button everytime. Also, I think an expiry of clipboard history should also be implemented. For example. the history only stores for a day and clears itself.

**Comment by joecks** [comment]
Thanks for the suggestion but I don't want teach the mainstream user to use that hacks. I believe google made this change with good intentions so let's try to make the best out of it.
